/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cashOnDelivery' : IDL.Null,
  'prepaid' : IDL.Null,
});
export const OrderedItem = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'customer' : IDL.Principal,
  'orderedItems' : IDL.Vec(OrderedItem),
  'orderId' : IDL.Nat,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PaymentSettings = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'ifscCode' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'upiId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderedItem),
        IDL.Nat,
        PaymentMethod,
      ],
      [IDL.Nat],
      [],
    ),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updatePaymentSettings' : IDL.Func([PaymentSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cashOnDelivery' : IDL.Null,
    'prepaid' : IDL.Null,
  });
  const OrderedItem = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'customer' : IDL.Principal,
    'orderedItems' : IDL.Vec(OrderedItem),
    'orderId' : IDL.Nat,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const PaymentSettings = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'ifscCode' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'upiId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCustomerOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderedItem),
          IDL.Nat,
          PaymentMethod,
        ],
        [IDL.Nat],
        [],
      ),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updatePaymentSettings' : IDL.Func([PaymentSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };